### ISSUE TITLE
TypeError: Cannot read property 'format' of undefined

### ISSUE THREAD

**Issue by DaveDaveDaveDave** [PfisterDaniel/node-red-contrib-apple-find-me#11]
The following fault occurred after a number of days of successful use of the node.

The error occurs now each time node-red loads.  Removal of the node rectifies the issue and allows node-red to load.
No node configuration changed from working to non-working.

```
19 Mar 22:16:28 - TypeError: Cannot read property 'format' of undefined
    at C:\Users\NODE\.node-red\node_modules\node-red-contrib-apple-find-me\nodes\apple-find-me.js:379:130
    at Array.forEach (<anonymous>)
    at C:\Users\NODE\.node-red\node_modules\node-red-contrib-apple-find-me\nodes\apple-find-me.js:356:46
    at done (C:\Users\NODE\.node-red\node_modules\urllib\lib\urllib.js:617:5)
    at C:\Users\NODE\.node-red\node_modules\urllib\lib\urllib.js:911:9
    at decodeContent (C:\Users\NODE\.node-red\node_modules\urllib\lib\urllib.js:699:14)
    at handleResponseCloseAndEnd (C:\Users\NODE\.node-red\node_modules\urllib\lib\urllib.js:876:7)
    at IncomingMessage.<anonymous> (C:\Users\NODE\.node-red\node_modules\urllib\lib\urllib.js:920:7)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
```

Thanks!

**Comment by PfisterDaniel** [comment]
I cannot reproduce. Can you say me your used Timezone and Time-Format?

Br Daniel

**Comment by DaveDaveDaveDave** [comment]
I deleted the account node and recreated, setting the timezone to local and leaving the Time-Format as the default. Now everything is working!

I should have tried this earlier.  Thanks!
